require: rubocop-performance
require: rubocop-rails

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 50
